version: "3.9"

services:
  web_service:
    image: php:7.2-apache
    container_name: php_apache
    ports:
      - 8082:80
    volumes:
      - /var/www/html:/var/www/html

  db_service:
    image: mariadb:latest
    container_name: mysql_apache
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database_apache
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword@123
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    